apiVersion: v1
kind: Service
metadata:
  name: amitfinalproject
spec:
  type: NodePort
  selector:
    app: amitfinalproject
  ports:
    - nodePort: 30000
      port: 80
      targetPort: 80
      protocol: TCP